/*
 * Generated by gdbus-codegen 2.33.12. DO NOT EDIT.
 *
 * The license of this code is the same as for the source it was derived from.
 */

#ifdef HAVE_CONFIG_H
#  include "config.h"
#endif

#include "remote-login.h"

#include <string.h>
#ifdef G_OS_UNIX
#  include <gio/gunixfdlist.h>
#endif

typedef struct
{
  GDBusArgInfo parent_struct;
  gboolean use_gvariant;
} _ExtendedGDBusArgInfo;

typedef struct
{
  GDBusMethodInfo parent_struct;
  const gchar *signal_name;
  gboolean pass_fdlist;
} _ExtendedGDBusMethodInfo;

typedef struct
{
  GDBusSignalInfo parent_struct;
  const gchar *signal_name;
} _ExtendedGDBusSignalInfo;

typedef struct
{
  GDBusPropertyInfo parent_struct;
  const gchar *hyphen_name;
  gboolean use_gvariant;
} _ExtendedGDBusPropertyInfo;

typedef struct
{
  GDBusInterfaceInfo parent_struct;
  const gchar *hyphen_name;
} _ExtendedGDBusInterfaceInfo;

typedef struct
{
  const _ExtendedGDBusPropertyInfo *info;
  guint prop_id;
  GValue orig_value; /* the value before the change */
} ChangedProperty;

static void
_changed_property_free (ChangedProperty *data)
{
  g_value_unset (&data->orig_value);
  g_free (data);
}

static gboolean
_g_strv_equal0 (gchar **a, gchar **b)
{
  gboolean ret = FALSE;
  guint n;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  if (g_strv_length (a) != g_strv_length (b))
    goto out;
  for (n = 0; a[n] != NULL; n++)
    if (g_strcmp0 (a[n], b[n]) != 0)
      goto out;
  ret = TRUE;
out:
  return ret;
}

static gboolean
_g_variant_equal0 (GVariant *a, GVariant *b)
{
  gboolean ret = FALSE;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  ret = g_variant_equal (a, b);
out:
  return ret;
}

G_GNUC_UNUSED static gboolean
_g_value_equal (const GValue *a, const GValue *b)
{
  gboolean ret = FALSE;
  g_assert (G_VALUE_TYPE (a) == G_VALUE_TYPE (b));
  switch (G_VALUE_TYPE (a))
    {
      case G_TYPE_BOOLEAN:
        ret = (g_value_get_boolean (a) == g_value_get_boolean (b));
        break;
      case G_TYPE_UCHAR:
        ret = (g_value_get_uchar (a) == g_value_get_uchar (b));
        break;
      case G_TYPE_INT:
        ret = (g_value_get_int (a) == g_value_get_int (b));
        break;
      case G_TYPE_UINT:
        ret = (g_value_get_uint (a) == g_value_get_uint (b));
        break;
      case G_TYPE_INT64:
        ret = (g_value_get_int64 (a) == g_value_get_int64 (b));
        break;
      case G_TYPE_UINT64:
        ret = (g_value_get_uint64 (a) == g_value_get_uint64 (b));
        break;
      case G_TYPE_DOUBLE:
        {
          /* Avoid -Wfloat-equal warnings by doing a direct bit compare */
          gdouble da = g_value_get_double (a);
          gdouble db = g_value_get_double (b);
          ret = memcmp (&da, &db, sizeof (gdouble)) == 0;
        }
        break;
      case G_TYPE_STRING:
        ret = (g_strcmp0 (g_value_get_string (a), g_value_get_string (b)) == 0);
        break;
      case G_TYPE_VARIANT:
        ret = _g_variant_equal0 (g_value_get_variant (a), g_value_get_variant (b));
        break;
      default:
        if (G_VALUE_TYPE (a) == G_TYPE_STRV)
          ret = _g_strv_equal0 (g_value_get_boxed (a), g_value_get_boxed (b));
        else
          g_critical ("_g_value_equal() does not handle type %s", g_type_name (G_VALUE_TYPE (a)));
        break;
    }
  return ret;
}

/* ------------------------------------------------------------------------
 * Code for interface com.canonical.RemoteLogin
 * ------------------------------------------------------------------------
 */

/**
 * SECTION:RemoteLogin
 * @title: RemoteLogin
 * @short_description: Generated C code for the com.canonical.RemoteLogin D-Bus interface
 *
 * This section contains code for working with the <link linkend="gdbus-interface-com-canonical-RemoteLogin.top_of_page">com.canonical.RemoteLogin</link> D-Bus interface in C.
 */

/* ---- Introspection data for com.canonical.RemoteLogin ---- */

static const _ExtendedGDBusArgInfo _remote_login_method_info_get_servers_OUT_ARG_serverList =
{
  {
    -1,
    (gchar *) "serverList",
    (gchar *) "a(sssba(sbva{sv})a(si))",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _remote_login_method_info_get_servers_OUT_ARG_pointers[] =
{
  &_remote_login_method_info_get_servers_OUT_ARG_serverList,
  NULL
};

static const _ExtendedGDBusMethodInfo _remote_login_method_info_get_servers =
{
  {
    -1,
    (gchar *) "GetServers",
    NULL,
    (GDBusArgInfo **) &_remote_login_method_info_get_servers_OUT_ARG_pointers,
    NULL
  },
  "handle-get-servers",
  FALSE
};

static const _ExtendedGDBusArgInfo _remote_login_method_info_get_servers_for_login_IN_ARG_uri =
{
  {
    -1,
    (gchar *) "uri",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _remote_login_method_info_get_servers_for_login_IN_ARG_emailAddress =
{
  {
    -1,
    (gchar *) "emailAddress",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _remote_login_method_info_get_servers_for_login_IN_ARG_password =
{
  {
    -1,
    (gchar *) "password",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _remote_login_method_info_get_servers_for_login_IN_ARG_allowCache =
{
  {
    -1,
    (gchar *) "allowCache",
    (gchar *) "b",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _remote_login_method_info_get_servers_for_login_IN_ARG_pointers[] =
{
  &_remote_login_method_info_get_servers_for_login_IN_ARG_uri,
  &_remote_login_method_info_get_servers_for_login_IN_ARG_emailAddress,
  &_remote_login_method_info_get_servers_for_login_IN_ARG_password,
  &_remote_login_method_info_get_servers_for_login_IN_ARG_allowCache,
  NULL
};

static const _ExtendedGDBusArgInfo _remote_login_method_info_get_servers_for_login_OUT_ARG_loginSuccess =
{
  {
    -1,
    (gchar *) "loginSuccess",
    (gchar *) "b",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _remote_login_method_info_get_servers_for_login_OUT_ARG_dataType =
{
  {
    -1,
    (gchar *) "dataType",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _remote_login_method_info_get_servers_for_login_OUT_ARG_serverList =
{
  {
    -1,
    (gchar *) "serverList",
    (gchar *) "a(sssba(sbva{sv})a(si))",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _remote_login_method_info_get_servers_for_login_OUT_ARG_pointers[] =
{
  &_remote_login_method_info_get_servers_for_login_OUT_ARG_loginSuccess,
  &_remote_login_method_info_get_servers_for_login_OUT_ARG_dataType,
  &_remote_login_method_info_get_servers_for_login_OUT_ARG_serverList,
  NULL
};

static const _ExtendedGDBusMethodInfo _remote_login_method_info_get_servers_for_login =
{
  {
    -1,
    (gchar *) "GetServersForLogin",
    (GDBusArgInfo **) &_remote_login_method_info_get_servers_for_login_IN_ARG_pointers,
    (GDBusArgInfo **) &_remote_login_method_info_get_servers_for_login_OUT_ARG_pointers,
    NULL
  },
  "handle-get-servers-for-login",
  FALSE
};

static const _ExtendedGDBusArgInfo _remote_login_method_info_get_cached_domains_for_server_IN_ARG_uri =
{
  {
    -1,
    (gchar *) "uri",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _remote_login_method_info_get_cached_domains_for_server_IN_ARG_pointers[] =
{
  &_remote_login_method_info_get_cached_domains_for_server_IN_ARG_uri,
  NULL
};

static const _ExtendedGDBusArgInfo _remote_login_method_info_get_cached_domains_for_server_OUT_ARG_domains =
{
  {
    -1,
    (gchar *) "domains",
    (gchar *) "as",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _remote_login_method_info_get_cached_domains_for_server_OUT_ARG_pointers[] =
{
  &_remote_login_method_info_get_cached_domains_for_server_OUT_ARG_domains,
  NULL
};

static const _ExtendedGDBusMethodInfo _remote_login_method_info_get_cached_domains_for_server =
{
  {
    -1,
    (gchar *) "GetCachedDomainsForServer",
    (GDBusArgInfo **) &_remote_login_method_info_get_cached_domains_for_server_IN_ARG_pointers,
    (GDBusArgInfo **) &_remote_login_method_info_get_cached_domains_for_server_OUT_ARG_pointers,
    NULL
  },
  "handle-get-cached-domains-for-server",
  FALSE
};

static const _ExtendedGDBusArgInfo _remote_login_method_info_set_applications_for_server_IN_ARG_uccsUri =
{
  {
    -1,
    (gchar *) "uccsUri",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _remote_login_method_info_set_applications_for_server_IN_ARG_serverUri =
{
  {
    -1,
    (gchar *) "serverUri",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _remote_login_method_info_set_applications_for_server_IN_ARG_applications =
{
  {
    -1,
    (gchar *) "applications",
    (gchar *) "a(si)",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _remote_login_method_info_set_applications_for_server_IN_ARG_pointers[] =
{
  &_remote_login_method_info_set_applications_for_server_IN_ARG_uccsUri,
  &_remote_login_method_info_set_applications_for_server_IN_ARG_serverUri,
  &_remote_login_method_info_set_applications_for_server_IN_ARG_applications,
  NULL
};

static const _ExtendedGDBusMethodInfo _remote_login_method_info_set_applications_for_server =
{
  {
    -1,
    (gchar *) "SetApplicationsForServer",
    (GDBusArgInfo **) &_remote_login_method_info_set_applications_for_server_IN_ARG_pointers,
    NULL,
    NULL
  },
  "handle-set-applications-for-server",
  FALSE
};

static const _ExtendedGDBusArgInfo _remote_login_method_info_set_last_used_server_IN_ARG_uccsUri =
{
  {
    -1,
    (gchar *) "uccsUri",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _remote_login_method_info_set_last_used_server_IN_ARG_serverUri =
{
  {
    -1,
    (gchar *) "serverUri",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _remote_login_method_info_set_last_used_server_IN_ARG_pointers[] =
{
  &_remote_login_method_info_set_last_used_server_IN_ARG_uccsUri,
  &_remote_login_method_info_set_last_used_server_IN_ARG_serverUri,
  NULL
};

static const _ExtendedGDBusMethodInfo _remote_login_method_info_set_last_used_server =
{
  {
    -1,
    (gchar *) "SetLastUsedServer",
    (GDBusArgInfo **) &_remote_login_method_info_set_last_used_server_IN_ARG_pointers,
    NULL,
    NULL
  },
  "handle-set-last-used-server",
  FALSE
};

static const _ExtendedGDBusMethodInfo * const _remote_login_method_info_pointers[] =
{
  &_remote_login_method_info_get_servers,
  &_remote_login_method_info_get_servers_for_login,
  &_remote_login_method_info_get_cached_domains_for_server,
  &_remote_login_method_info_set_applications_for_server,
  &_remote_login_method_info_set_last_used_server,
  NULL
};

static const _ExtendedGDBusArgInfo _remote_login_signal_info_servers_updated_ARG_serverList =
{
  {
    -1,
    (gchar *) "serverList",
    (gchar *) "a(sssba(sbva{sv})a(si))",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _remote_login_signal_info_servers_updated_ARG_pointers[] =
{
  &_remote_login_signal_info_servers_updated_ARG_serverList,
  NULL
};

static const _ExtendedGDBusSignalInfo _remote_login_signal_info_servers_updated =
{
  {
    -1,
    (gchar *) "ServersUpdated",
    (GDBusArgInfo **) &_remote_login_signal_info_servers_updated_ARG_pointers,
    NULL
  },
  "servers-updated"
};

static const _ExtendedGDBusArgInfo _remote_login_signal_info_login_servers_updated_ARG_uri =
{
  {
    -1,
    (gchar *) "uri",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _remote_login_signal_info_login_servers_updated_ARG_emailAddress =
{
  {
    -1,
    (gchar *) "emailAddress",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _remote_login_signal_info_login_servers_updated_ARG_dataType =
{
  {
    -1,
    (gchar *) "dataType",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _remote_login_signal_info_login_servers_updated_ARG_serverList =
{
  {
    -1,
    (gchar *) "serverList",
    (gchar *) "a(sssba(sbva{sv})a(si))",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _remote_login_signal_info_login_servers_updated_ARG_pointers[] =
{
  &_remote_login_signal_info_login_servers_updated_ARG_uri,
  &_remote_login_signal_info_login_servers_updated_ARG_emailAddress,
  &_remote_login_signal_info_login_servers_updated_ARG_dataType,
  &_remote_login_signal_info_login_servers_updated_ARG_serverList,
  NULL
};

static const _ExtendedGDBusSignalInfo _remote_login_signal_info_login_servers_updated =
{
  {
    -1,
    (gchar *) "LoginServersUpdated",
    (GDBusArgInfo **) &_remote_login_signal_info_login_servers_updated_ARG_pointers,
    NULL
  },
  "login-servers-updated"
};

static const _ExtendedGDBusArgInfo _remote_login_signal_info_login_changed_ARG_uri =
{
  {
    -1,
    (gchar *) "uri",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _remote_login_signal_info_login_changed_ARG_emailAddress =
{
  {
    -1,
    (gchar *) "emailAddress",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _remote_login_signal_info_login_changed_ARG_pointers[] =
{
  &_remote_login_signal_info_login_changed_ARG_uri,
  &_remote_login_signal_info_login_changed_ARG_emailAddress,
  NULL
};

static const _ExtendedGDBusSignalInfo _remote_login_signal_info_login_changed =
{
  {
    -1,
    (gchar *) "LoginChanged",
    (GDBusArgInfo **) &_remote_login_signal_info_login_changed_ARG_pointers,
    NULL
  },
  "login-changed"
};

static const _ExtendedGDBusSignalInfo * const _remote_login_signal_info_pointers[] =
{
  &_remote_login_signal_info_servers_updated,
  &_remote_login_signal_info_login_servers_updated,
  &_remote_login_signal_info_login_changed,
  NULL
};

static const _ExtendedGDBusInterfaceInfo _remote_login_interface_info =
{
  {
    -1,
    (gchar *) "com.canonical.RemoteLogin",
    (GDBusMethodInfo **) &_remote_login_method_info_pointers,
    (GDBusSignalInfo **) &_remote_login_signal_info_pointers,
    NULL,
    NULL
  },
  "remote-login",
};


/**
 * remote_login_interface_info:
 *
 * Gets a machine-readable description of the <link linkend="gdbus-interface-com-canonical-RemoteLogin.top_of_page">com.canonical.RemoteLogin</link> D-Bus interface.
 *
 * Returns: (transfer none): A #GDBusInterfaceInfo. Do not free.
 */
GDBusInterfaceInfo *
remote_login_interface_info (void)
{
  return (GDBusInterfaceInfo *) &_remote_login_interface_info.parent_struct;
}

/**
 * remote_login_override_properties:
 * @klass: The class structure for a #GObject<!-- -->-derived class.
 * @property_id_begin: The property id to assign to the first overridden property.
 *
 * Overrides all #GObject properties in the #RemoteLogin interface for a concrete class.
 * The properties are overridden in the order they are defined.
 *
 * Returns: The last property id.
 */
guint
remote_login_override_properties (GObjectClass *klass, guint property_id_begin)
{
  return property_id_begin - 1;
}



/**
 * RemoteLogin:
 *
 * Abstract interface type for the D-Bus interface <link linkend="gdbus-interface-com-canonical-RemoteLogin.top_of_page">com.canonical.RemoteLogin</link>.
 */

/**
 * RemoteLoginIface:
 * @parent_iface: The parent interface.
 * @handle_get_cached_domains_for_server: Handler for the #RemoteLogin::handle-get-cached-domains-for-server signal.
 * @handle_get_servers: Handler for the #RemoteLogin::handle-get-servers signal.
 * @handle_get_servers_for_login: Handler for the #RemoteLogin::handle-get-servers-for-login signal.
 * @handle_set_applications_for_server: Handler for the #RemoteLogin::handle-set-applications-for-server signal.
 * @handle_set_last_used_server: Handler for the #RemoteLogin::handle-set-last-used-server signal.
 * @login_changed: Handler for the #RemoteLogin::login-changed signal.
 * @login_servers_updated: Handler for the #RemoteLogin::login-servers-updated signal.
 * @servers_updated: Handler for the #RemoteLogin::servers-updated signal.
 *
 * Virtual table for the D-Bus interface <link linkend="gdbus-interface-com-canonical-RemoteLogin.top_of_page">com.canonical.RemoteLogin</link>.
 */

static void
remote_login_default_init (RemoteLoginIface *iface)
{
  /* GObject signals for incoming D-Bus method calls: */
  /**
   * RemoteLogin::handle-get-servers:
   * @object: A #RemoteLogin.
   * @invocation: A #GDBusMethodInvocation.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-com-canonical-RemoteLogin.GetServers">GetServers()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call remote_login_complete_get_servers() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-get-servers",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (RemoteLoginIface, handle_get_servers),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    1,
    G_TYPE_DBUS_METHOD_INVOCATION);

  /**
   * RemoteLogin::handle-get-servers-for-login:
   * @object: A #RemoteLogin.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_uri: Argument passed by remote caller.
   * @arg_emailAddress: Argument passed by remote caller.
   * @arg_password: Argument passed by remote caller.
   * @arg_allowCache: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-com-canonical-RemoteLogin.GetServersForLogin">GetServersForLogin()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call remote_login_complete_get_servers_for_login() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-get-servers-for-login",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (RemoteLoginIface, handle_get_servers_for_login),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    5,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_STRING, G_TYPE_STRING, G_TYPE_STRING, G_TYPE_BOOLEAN);

  /**
   * RemoteLogin::handle-get-cached-domains-for-server:
   * @object: A #RemoteLogin.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_uri: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-com-canonical-RemoteLogin.GetCachedDomainsForServer">GetCachedDomainsForServer()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call remote_login_complete_get_cached_domains_for_server() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-get-cached-domains-for-server",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (RemoteLoginIface, handle_get_cached_domains_for_server),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    2,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_STRING);

  /**
   * RemoteLogin::handle-set-applications-for-server:
   * @object: A #RemoteLogin.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_uccsUri: Argument passed by remote caller.
   * @arg_serverUri: Argument passed by remote caller.
   * @arg_applications: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-com-canonical-RemoteLogin.SetApplicationsForServer">SetApplicationsForServer()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call remote_login_complete_set_applications_for_server() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-set-applications-for-server",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (RemoteLoginIface, handle_set_applications_for_server),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    4,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_STRING, G_TYPE_STRING, G_TYPE_VARIANT);

  /**
   * RemoteLogin::handle-set-last-used-server:
   * @object: A #RemoteLogin.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_uccsUri: Argument passed by remote caller.
   * @arg_serverUri: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-com-canonical-RemoteLogin.SetLastUsedServer">SetLastUsedServer()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call remote_login_complete_set_last_used_server() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-set-last-used-server",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (RemoteLoginIface, handle_set_last_used_server),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    3,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_STRING, G_TYPE_STRING);

  /* GObject signals for received D-Bus signals: */
  /**
   * RemoteLogin::servers-updated:
   * @object: A #RemoteLogin.
   * @arg_serverList: Argument.
   *
   * On the client-side, this signal is emitted whenever the D-Bus signal <link linkend="gdbus-signal-com-canonical-RemoteLogin.ServersUpdated">"ServersUpdated"</link> is received.
   *
   * On the service-side, this signal can be used with e.g. g_signal_emit_by_name() to make the object emit the D-Bus signal.
   */
  g_signal_new ("servers-updated",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (RemoteLoginIface, servers_updated),
    NULL,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_NONE,
    1, G_TYPE_VARIANT);

  /**
   * RemoteLogin::login-servers-updated:
   * @object: A #RemoteLogin.
   * @arg_uri: Argument.
   * @arg_emailAddress: Argument.
   * @arg_dataType: Argument.
   * @arg_serverList: Argument.
   *
   * On the client-side, this signal is emitted whenever the D-Bus signal <link linkend="gdbus-signal-com-canonical-RemoteLogin.LoginServersUpdated">"LoginServersUpdated"</link> is received.
   *
   * On the service-side, this signal can be used with e.g. g_signal_emit_by_name() to make the object emit the D-Bus signal.
   */
  g_signal_new ("login-servers-updated",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (RemoteLoginIface, login_servers_updated),
    NULL,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_NONE,
    4, G_TYPE_STRING, G_TYPE_STRING, G_TYPE_STRING, G_TYPE_VARIANT);

  /**
   * RemoteLogin::login-changed:
   * @object: A #RemoteLogin.
   * @arg_uri: Argument.
   * @arg_emailAddress: Argument.
   *
   * On the client-side, this signal is emitted whenever the D-Bus signal <link linkend="gdbus-signal-com-canonical-RemoteLogin.LoginChanged">"LoginChanged"</link> is received.
   *
   * On the service-side, this signal can be used with e.g. g_signal_emit_by_name() to make the object emit the D-Bus signal.
   */
  g_signal_new ("login-changed",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (RemoteLoginIface, login_changed),
    NULL,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_NONE,
    2, G_TYPE_STRING, G_TYPE_STRING);

}

typedef RemoteLoginIface RemoteLoginInterface;
G_DEFINE_INTERFACE (RemoteLogin, remote_login, G_TYPE_OBJECT);

/**
 * remote_login_emit_servers_updated:
 * @object: A #RemoteLogin.
 * @arg_serverList: Argument to pass with the signal.
 *
 * Emits the <link linkend="gdbus-signal-com-canonical-RemoteLogin.ServersUpdated">"ServersUpdated"</link> D-Bus signal.
 */
void
remote_login_emit_servers_updated (
    RemoteLogin *object,
    GVariant *arg_serverList)
{
  g_signal_emit_by_name (object, "servers-updated", arg_serverList);
}

/**
 * remote_login_emit_login_servers_updated:
 * @object: A #RemoteLogin.
 * @arg_uri: Argument to pass with the signal.
 * @arg_emailAddress: Argument to pass with the signal.
 * @arg_dataType: Argument to pass with the signal.
 * @arg_serverList: Argument to pass with the signal.
 *
 * Emits the <link linkend="gdbus-signal-com-canonical-RemoteLogin.LoginServersUpdated">"LoginServersUpdated"</link> D-Bus signal.
 */
void
remote_login_emit_login_servers_updated (
    RemoteLogin *object,
    const gchar *arg_uri,
    const gchar *arg_emailAddress,
    const gchar *arg_dataType,
    GVariant *arg_serverList)
{
  g_signal_emit_by_name (object, "login-servers-updated", arg_uri, arg_emailAddress, arg_dataType, arg_serverList);
}

/**
 * remote_login_emit_login_changed:
 * @object: A #RemoteLogin.
 * @arg_uri: Argument to pass with the signal.
 * @arg_emailAddress: Argument to pass with the signal.
 *
 * Emits the <link linkend="gdbus-signal-com-canonical-RemoteLogin.LoginChanged">"LoginChanged"</link> D-Bus signal.
 */
void
remote_login_emit_login_changed (
    RemoteLogin *object,
    const gchar *arg_uri,
    const gchar *arg_emailAddress)
{
  g_signal_emit_by_name (object, "login-changed", arg_uri, arg_emailAddress);
}

/**
 * remote_login_call_get_servers:
 * @proxy: A #RemoteLoginProxy.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-com-canonical-RemoteLogin.GetServers">GetServers()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call remote_login_call_get_servers_finish() to get the result of the operation.
 *
 * See remote_login_call_get_servers_sync() for the synchronous, blocking version of this method.
 */
void
remote_login_call_get_servers (
    RemoteLogin *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "GetServers",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * remote_login_call_get_servers_finish:
 * @proxy: A #RemoteLoginProxy.
 * @out_serverList: (out): Return location for return parameter or %NULL to ignore.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to remote_login_call_get_servers().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with remote_login_call_get_servers().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
remote_login_call_get_servers_finish (
    RemoteLogin *proxy,
    GVariant **out_serverList,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(@a(sssba(sbva{sv})a(si)))",
                 out_serverList);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * remote_login_call_get_servers_sync:
 * @proxy: A #RemoteLoginProxy.
 * @out_serverList: (out): Return location for return parameter or %NULL to ignore.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-com-canonical-RemoteLogin.GetServers">GetServers()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See remote_login_call_get_servers() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
remote_login_call_get_servers_sync (
    RemoteLogin *proxy,
    GVariant **out_serverList,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "GetServers",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(@a(sssba(sbva{sv})a(si)))",
                 out_serverList);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * remote_login_call_get_servers_for_login:
 * @proxy: A #RemoteLoginProxy.
 * @arg_uri: Argument to pass with the method invocation.
 * @arg_emailAddress: Argument to pass with the method invocation.
 * @arg_password: Argument to pass with the method invocation.
 * @arg_allowCache: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-com-canonical-RemoteLogin.GetServersForLogin">GetServersForLogin()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call remote_login_call_get_servers_for_login_finish() to get the result of the operation.
 *
 * See remote_login_call_get_servers_for_login_sync() for the synchronous, blocking version of this method.
 */
void
remote_login_call_get_servers_for_login (
    RemoteLogin *proxy,
    const gchar *arg_uri,
    const gchar *arg_emailAddress,
    const gchar *arg_password,
    gboolean arg_allowCache,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "GetServersForLogin",
    g_variant_new ("(sssb)",
                   arg_uri,
                   arg_emailAddress,
                   arg_password,
                   arg_allowCache),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * remote_login_call_get_servers_for_login_finish:
 * @proxy: A #RemoteLoginProxy.
 * @out_loginSuccess: (out): Return location for return parameter or %NULL to ignore.
 * @out_dataType: (out): Return location for return parameter or %NULL to ignore.
 * @out_serverList: (out): Return location for return parameter or %NULL to ignore.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to remote_login_call_get_servers_for_login().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with remote_login_call_get_servers_for_login().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
remote_login_call_get_servers_for_login_finish (
    RemoteLogin *proxy,
    gboolean *out_loginSuccess,
    gchar **out_dataType,
    GVariant **out_serverList,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(bs@a(sssba(sbva{sv})a(si)))",
                 out_loginSuccess,
                 out_dataType,
                 out_serverList);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * remote_login_call_get_servers_for_login_sync:
 * @proxy: A #RemoteLoginProxy.
 * @arg_uri: Argument to pass with the method invocation.
 * @arg_emailAddress: Argument to pass with the method invocation.
 * @arg_password: Argument to pass with the method invocation.
 * @arg_allowCache: Argument to pass with the method invocation.
 * @out_loginSuccess: (out): Return location for return parameter or %NULL to ignore.
 * @out_dataType: (out): Return location for return parameter or %NULL to ignore.
 * @out_serverList: (out): Return location for return parameter or %NULL to ignore.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-com-canonical-RemoteLogin.GetServersForLogin">GetServersForLogin()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See remote_login_call_get_servers_for_login() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
remote_login_call_get_servers_for_login_sync (
    RemoteLogin *proxy,
    const gchar *arg_uri,
    const gchar *arg_emailAddress,
    const gchar *arg_password,
    gboolean arg_allowCache,
    gboolean *out_loginSuccess,
    gchar **out_dataType,
    GVariant **out_serverList,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "GetServersForLogin",
    g_variant_new ("(sssb)",
                   arg_uri,
                   arg_emailAddress,
                   arg_password,
                   arg_allowCache),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(bs@a(sssba(sbva{sv})a(si)))",
                 out_loginSuccess,
                 out_dataType,
                 out_serverList);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * remote_login_call_get_cached_domains_for_server:
 * @proxy: A #RemoteLoginProxy.
 * @arg_uri: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-com-canonical-RemoteLogin.GetCachedDomainsForServer">GetCachedDomainsForServer()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call remote_login_call_get_cached_domains_for_server_finish() to get the result of the operation.
 *
 * See remote_login_call_get_cached_domains_for_server_sync() for the synchronous, blocking version of this method.
 */
void
remote_login_call_get_cached_domains_for_server (
    RemoteLogin *proxy,
    const gchar *arg_uri,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "GetCachedDomainsForServer",
    g_variant_new ("(s)",
                   arg_uri),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * remote_login_call_get_cached_domains_for_server_finish:
 * @proxy: A #RemoteLoginProxy.
 * @out_domains: (out): Return location for return parameter or %NULL to ignore.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to remote_login_call_get_cached_domains_for_server().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with remote_login_call_get_cached_domains_for_server().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
remote_login_call_get_cached_domains_for_server_finish (
    RemoteLogin *proxy,
    gchar ***out_domains,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(^as)",
                 out_domains);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * remote_login_call_get_cached_domains_for_server_sync:
 * @proxy: A #RemoteLoginProxy.
 * @arg_uri: Argument to pass with the method invocation.
 * @out_domains: (out): Return location for return parameter or %NULL to ignore.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-com-canonical-RemoteLogin.GetCachedDomainsForServer">GetCachedDomainsForServer()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See remote_login_call_get_cached_domains_for_server() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
remote_login_call_get_cached_domains_for_server_sync (
    RemoteLogin *proxy,
    const gchar *arg_uri,
    gchar ***out_domains,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "GetCachedDomainsForServer",
    g_variant_new ("(s)",
                   arg_uri),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(^as)",
                 out_domains);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * remote_login_call_set_applications_for_server:
 * @proxy: A #RemoteLoginProxy.
 * @arg_uccsUri: Argument to pass with the method invocation.
 * @arg_serverUri: Argument to pass with the method invocation.
 * @arg_applications: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-com-canonical-RemoteLogin.SetApplicationsForServer">SetApplicationsForServer()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call remote_login_call_set_applications_for_server_finish() to get the result of the operation.
 *
 * See remote_login_call_set_applications_for_server_sync() for the synchronous, blocking version of this method.
 */
void
remote_login_call_set_applications_for_server (
    RemoteLogin *proxy,
    const gchar *arg_uccsUri,
    const gchar *arg_serverUri,
    GVariant *arg_applications,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "SetApplicationsForServer",
    g_variant_new ("(ss@a(si))",
                   arg_uccsUri,
                   arg_serverUri,
                   arg_applications),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * remote_login_call_set_applications_for_server_finish:
 * @proxy: A #RemoteLoginProxy.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to remote_login_call_set_applications_for_server().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with remote_login_call_set_applications_for_server().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
remote_login_call_set_applications_for_server_finish (
    RemoteLogin *proxy,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * remote_login_call_set_applications_for_server_sync:
 * @proxy: A #RemoteLoginProxy.
 * @arg_uccsUri: Argument to pass with the method invocation.
 * @arg_serverUri: Argument to pass with the method invocation.
 * @arg_applications: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-com-canonical-RemoteLogin.SetApplicationsForServer">SetApplicationsForServer()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See remote_login_call_set_applications_for_server() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
remote_login_call_set_applications_for_server_sync (
    RemoteLogin *proxy,
    const gchar *arg_uccsUri,
    const gchar *arg_serverUri,
    GVariant *arg_applications,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "SetApplicationsForServer",
    g_variant_new ("(ss@a(si))",
                   arg_uccsUri,
                   arg_serverUri,
                   arg_applications),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * remote_login_call_set_last_used_server:
 * @proxy: A #RemoteLoginProxy.
 * @arg_uccsUri: Argument to pass with the method invocation.
 * @arg_serverUri: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-com-canonical-RemoteLogin.SetLastUsedServer">SetLastUsedServer()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call remote_login_call_set_last_used_server_finish() to get the result of the operation.
 *
 * See remote_login_call_set_last_used_server_sync() for the synchronous, blocking version of this method.
 */
void
remote_login_call_set_last_used_server (
    RemoteLogin *proxy,
    const gchar *arg_uccsUri,
    const gchar *arg_serverUri,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "SetLastUsedServer",
    g_variant_new ("(ss)",
                   arg_uccsUri,
                   arg_serverUri),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * remote_login_call_set_last_used_server_finish:
 * @proxy: A #RemoteLoginProxy.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to remote_login_call_set_last_used_server().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with remote_login_call_set_last_used_server().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
remote_login_call_set_last_used_server_finish (
    RemoteLogin *proxy,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * remote_login_call_set_last_used_server_sync:
 * @proxy: A #RemoteLoginProxy.
 * @arg_uccsUri: Argument to pass with the method invocation.
 * @arg_serverUri: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-com-canonical-RemoteLogin.SetLastUsedServer">SetLastUsedServer()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See remote_login_call_set_last_used_server() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
remote_login_call_set_last_used_server_sync (
    RemoteLogin *proxy,
    const gchar *arg_uccsUri,
    const gchar *arg_serverUri,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "SetLastUsedServer",
    g_variant_new ("(ss)",
                   arg_uccsUri,
                   arg_serverUri),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * remote_login_complete_get_servers:
 * @object: A #RemoteLogin.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 * @serverList: Parameter to return.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-com-canonical-RemoteLogin.GetServers">GetServers()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
remote_login_complete_get_servers (
    RemoteLogin *object,
    GDBusMethodInvocation *invocation,
    GVariant *serverList)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("(@a(sssba(sbva{sv})a(si)))",
                   serverList));
}

/**
 * remote_login_complete_get_servers_for_login:
 * @object: A #RemoteLogin.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 * @loginSuccess: Parameter to return.
 * @dataType: Parameter to return.
 * @serverList: Parameter to return.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-com-canonical-RemoteLogin.GetServersForLogin">GetServersForLogin()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
remote_login_complete_get_servers_for_login (
    RemoteLogin *object,
    GDBusMethodInvocation *invocation,
    gboolean loginSuccess,
    const gchar *dataType,
    GVariant *serverList)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("(bs@a(sssba(sbva{sv})a(si)))",
                   loginSuccess,
                   dataType,
                   serverList));
}

/**
 * remote_login_complete_get_cached_domains_for_server:
 * @object: A #RemoteLogin.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 * @domains: Parameter to return.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-com-canonical-RemoteLogin.GetCachedDomainsForServer">GetCachedDomainsForServer()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
remote_login_complete_get_cached_domains_for_server (
    RemoteLogin *object,
    GDBusMethodInvocation *invocation,
    const gchar *const *domains)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("(^as)",
                   domains));
}

/**
 * remote_login_complete_set_applications_for_server:
 * @object: A #RemoteLogin.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-com-canonical-RemoteLogin.SetApplicationsForServer">SetApplicationsForServer()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
remote_login_complete_set_applications_for_server (
    RemoteLogin *object,
    GDBusMethodInvocation *invocation)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("()"));
}

/**
 * remote_login_complete_set_last_used_server:
 * @object: A #RemoteLogin.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-com-canonical-RemoteLogin.SetLastUsedServer">SetLastUsedServer()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
remote_login_complete_set_last_used_server (
    RemoteLogin *object,
    GDBusMethodInvocation *invocation)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("()"));
}

/* ------------------------------------------------------------------------ */

/**
 * RemoteLoginProxy:
 *
 * The #RemoteLoginProxy structure contains only private data and should only be accessed using the provided API.
 */

/**
 * RemoteLoginProxyClass:
 * @parent_class: The parent class.
 *
 * Class structure for #RemoteLoginProxy.
 */

struct _RemoteLoginProxyPrivate
{
  GData *qdata;
};

static void remote_login_proxy_iface_init (RemoteLoginIface *iface);

G_DEFINE_TYPE_WITH_CODE (RemoteLoginProxy, remote_login_proxy, G_TYPE_DBUS_PROXY,
                         G_IMPLEMENT_INTERFACE (TYPE_REMOTE_LOGIN, remote_login_proxy_iface_init));

static void
remote_login_proxy_finalize (GObject *object)
{
  RemoteLoginProxy *proxy = REMOTE_LOGIN_PROXY (object);
  g_datalist_clear (&proxy->priv->qdata);
  G_OBJECT_CLASS (remote_login_proxy_parent_class)->finalize (object);
}

static void
remote_login_proxy_get_property (GObject      *object,
  guint         prop_id,
  GValue       *value,
  GParamSpec   *pspec)
{
}

static void
remote_login_proxy_set_property (GObject      *object,
  guint         prop_id,
  const GValue *value,
  GParamSpec   *pspec)
{
}

static void
remote_login_proxy_g_signal (GDBusProxy *proxy,
  const gchar *sender_name,
  const gchar *signal_name,
  GVariant *parameters)
{
  _ExtendedGDBusSignalInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  guint num_params;
  guint n;
  guint signal_id;
  info = (_ExtendedGDBusSignalInfo *) g_dbus_interface_info_lookup_signal ((GDBusInterfaceInfo *) &_remote_login_interface_info.parent_struct, signal_name);
  if (info == NULL)
    return;
  num_params = g_variant_n_children (parameters);
  paramv = g_new0 (GValue, num_params + 1);
  g_value_init (&paramv[0], TYPE_REMOTE_LOGIN);
  g_value_set_object (&paramv[0], proxy);
  g_variant_iter_init (&iter, parameters);
  n = 1;
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.args[n - 1];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, TYPE_REMOTE_LOGIN);
  g_signal_emitv (paramv, signal_id, 0, NULL);
  for (n = 0; n < num_params + 1; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static void
remote_login_proxy_g_properties_changed (GDBusProxy *_proxy,
  GVariant *changed_properties,
  const gchar *const *invalidated_properties)
{
  RemoteLoginProxy *proxy = REMOTE_LOGIN_PROXY (_proxy);
  guint n;
  const gchar *key;
  GVariantIter *iter;
  _ExtendedGDBusPropertyInfo *info;
  g_variant_get (changed_properties, "a{sv}", &iter);
  while (g_variant_iter_next (iter, "{&sv}", &key, NULL))
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_remote_login_interface_info.parent_struct, key);
      g_datalist_remove_data (&proxy->priv->qdata, key);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
  g_variant_iter_free (iter);
  for (n = 0; invalidated_properties[n] != NULL; n++)
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_remote_login_interface_info.parent_struct, invalidated_properties[n]);
      g_datalist_remove_data (&proxy->priv->qdata, invalidated_properties[n]);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
}

static void
remote_login_proxy_init (RemoteLoginProxy *proxy)
{
  proxy->priv = G_TYPE_INSTANCE_GET_PRIVATE (proxy, TYPE_REMOTE_LOGIN_PROXY, RemoteLoginProxyPrivate);
  g_dbus_proxy_set_interface_info (G_DBUS_PROXY (proxy), remote_login_interface_info ());
}

static void
remote_login_proxy_class_init (RemoteLoginProxyClass *klass)
{
  GObjectClass *gobject_class;
  GDBusProxyClass *proxy_class;

  g_type_class_add_private (klass, sizeof (RemoteLoginProxyPrivate));

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize     = remote_login_proxy_finalize;
  gobject_class->get_property = remote_login_proxy_get_property;
  gobject_class->set_property = remote_login_proxy_set_property;

  proxy_class = G_DBUS_PROXY_CLASS (klass);
  proxy_class->g_signal = remote_login_proxy_g_signal;
  proxy_class->g_properties_changed = remote_login_proxy_g_properties_changed;

}

static void
remote_login_proxy_iface_init (RemoteLoginIface *iface)
{
}

/**
 * remote_login_proxy_new:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (allow-none): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-com-canonical-RemoteLogin.top_of_page">com.canonical.RemoteLogin</link>. See g_dbus_proxy_new() for more details.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call remote_login_proxy_new_finish() to get the result of the operation.
 *
 * See remote_login_proxy_new_sync() for the synchronous, blocking version of this constructor.
 */
void
remote_login_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (TYPE_REMOTE_LOGIN_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "com.canonical.RemoteLogin", NULL);
}

/**
 * remote_login_proxy_new_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to remote_login_proxy_new().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with remote_login_proxy_new().
 *
 * Returns: (transfer full) (type RemoteLoginProxy): The constructed proxy object or %NULL if @error is set.
 */
RemoteLogin *
remote_login_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return REMOTE_LOGIN (ret);
  else
    return NULL;
}

/**
 * remote_login_proxy_new_sync:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (allow-none): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Synchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-com-canonical-RemoteLogin.top_of_page">com.canonical.RemoteLogin</link>. See g_dbus_proxy_new_sync() for more details.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See remote_login_proxy_new() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type RemoteLoginProxy): The constructed proxy object or %NULL if @error is set.
 */
RemoteLogin *
remote_login_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (TYPE_REMOTE_LOGIN_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "com.canonical.RemoteLogin", NULL);
  if (ret != NULL)
    return REMOTE_LOGIN (ret);
  else
    return NULL;
}


/**
 * remote_login_proxy_new_for_bus:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Like remote_login_proxy_new() but takes a #GBusType instead of a #GDBusConnection.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call remote_login_proxy_new_for_bus_finish() to get the result of the operation.
 *
 * See remote_login_proxy_new_for_bus_sync() for the synchronous, blocking version of this constructor.
 */
void
remote_login_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (TYPE_REMOTE_LOGIN_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "com.canonical.RemoteLogin", NULL);
}

/**
 * remote_login_proxy_new_for_bus_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to remote_login_proxy_new_for_bus().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with remote_login_proxy_new_for_bus().
 *
 * Returns: (transfer full) (type RemoteLoginProxy): The constructed proxy object or %NULL if @error is set.
 */
RemoteLogin *
remote_login_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return REMOTE_LOGIN (ret);
  else
    return NULL;
}

/**
 * remote_login_proxy_new_for_bus_sync:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Like remote_login_proxy_new_sync() but takes a #GBusType instead of a #GDBusConnection.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See remote_login_proxy_new_for_bus() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type RemoteLoginProxy): The constructed proxy object or %NULL if @error is set.
 */
RemoteLogin *
remote_login_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (TYPE_REMOTE_LOGIN_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "com.canonical.RemoteLogin", NULL);
  if (ret != NULL)
    return REMOTE_LOGIN (ret);
  else
    return NULL;
}


/* ------------------------------------------------------------------------ */

/**
 * RemoteLoginSkeleton:
 *
 * The #RemoteLoginSkeleton structure contains only private data and should only be accessed using the provided API.
 */

/**
 * RemoteLoginSkeletonClass:
 * @parent_class: The parent class.
 *
 * Class structure for #RemoteLoginSkeleton.
 */

struct _RemoteLoginSkeletonPrivate
{
  GValue *properties;
  GList *changed_properties;
  GSource *changed_properties_idle_source;
  GMainContext *context;
  GMutex lock;
};

static void
_remote_login_skeleton_handle_method_call (
  GDBusConnection *connection,
  const gchar *sender,
  const gchar *object_path,
  const gchar *interface_name,
  const gchar *method_name,
  GVariant *parameters,
  GDBusMethodInvocation *invocation,
  gpointer user_data)
{
  RemoteLoginSkeleton *skeleton = REMOTE_LOGIN_SKELETON (user_data);
  _ExtendedGDBusMethodInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  guint num_params;
  guint num_extra;
  guint n;
  guint signal_id;
  GValue return_value = G_VALUE_INIT;
  info = (_ExtendedGDBusMethodInfo *) g_dbus_method_invocation_get_method_info (invocation);
  g_assert (info != NULL);
  num_params = g_variant_n_children (parameters);
  num_extra = info->pass_fdlist ? 3 : 2;  paramv = g_new0 (GValue, num_params + num_extra);
  n = 0;
  g_value_init (&paramv[n], TYPE_REMOTE_LOGIN);
  g_value_set_object (&paramv[n++], skeleton);
  g_value_init (&paramv[n], G_TYPE_DBUS_METHOD_INVOCATION);
  g_value_set_object (&paramv[n++], invocation);
  if (info->pass_fdlist)
    {
#ifdef G_OS_UNIX
      g_value_init (&paramv[n], G_TYPE_UNIX_FD_LIST);
      g_value_set_object (&paramv[n++], g_dbus_message_get_unix_fd_list (g_dbus_method_invocation_get_message (invocation)));
#else
      g_assert_not_reached ();
#endif
    }
  g_variant_iter_init (&iter, parameters);
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.in_args[n - num_extra];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, TYPE_REMOTE_LOGIN);
  g_value_init (&return_value, G_TYPE_BOOLEAN);
  g_signal_emitv (paramv, signal_id, 0, &return_value);
  if (!g_value_get_boolean (&return_value))
    g_dbus_method_invocation_return_error (invocation, G_DBUS_ERROR, G_DBUS_ERROR_UNKNOWN_METHOD, "Method %s is not implemented on interface %s", method_name, interface_name);
  g_value_unset (&return_value);
  for (n = 0; n < num_params + num_extra; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static GVariant *
_remote_login_skeleton_handle_get_property (
  GDBusConnection *connection,
  const gchar *sender,
  const gchar *object_path,
  const gchar *interface_name,
  const gchar *property_name,
  GError **error,
  gpointer user_data)
{
  RemoteLoginSkeleton *skeleton = REMOTE_LOGIN_SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  GVariant *ret;
  ret = NULL;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_remote_login_interface_info.parent_struct, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      g_value_init (&value, pspec->value_type);
      g_object_get_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      ret = g_dbus_gvalue_to_gvariant (&value, G_VARIANT_TYPE (info->parent_struct.signature));
      g_value_unset (&value);
    }
  return ret;
}

static gboolean
_remote_login_skeleton_handle_set_property (
  GDBusConnection *connection,
  const gchar *sender,
  const gchar *object_path,
  const gchar *interface_name,
  const gchar *property_name,
  GVariant *variant,
  GError **error,
  gpointer user_data)
{
  RemoteLoginSkeleton *skeleton = REMOTE_LOGIN_SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  gboolean ret;
  ret = FALSE;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_remote_login_interface_info.parent_struct, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      if (info->use_gvariant)
        g_value_set_variant (&value, variant);
      else
        g_dbus_gvariant_to_gvalue (variant, &value);
      g_object_set_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      g_value_unset (&value);
      ret = TRUE;
    }
  return ret;
}

static const GDBusInterfaceVTable _remote_login_skeleton_vtable =
{
  _remote_login_skeleton_handle_method_call,
  _remote_login_skeleton_handle_get_property,
  _remote_login_skeleton_handle_set_property
};

static GDBusInterfaceInfo *
remote_login_skeleton_dbus_interface_get_info (GDBusInterfaceSkeleton *skeleton)
{
  return remote_login_interface_info ();
}

static GDBusInterfaceVTable *
remote_login_skeleton_dbus_interface_get_vtable (GDBusInterfaceSkeleton *skeleton)
{
  return (GDBusInterfaceVTable *) &_remote_login_skeleton_vtable;
}

static GVariant *
remote_login_skeleton_dbus_interface_get_properties (GDBusInterfaceSkeleton *_skeleton)
{
  RemoteLoginSkeleton *skeleton = REMOTE_LOGIN_SKELETON (_skeleton);

  GVariantBuilder builder;
  guint n;
  g_variant_builder_init (&builder, G_VARIANT_TYPE ("a{sv}"));
  if (_remote_login_interface_info.parent_struct.properties == NULL)
    goto out;
  for (n = 0; _remote_login_interface_info.parent_struct.properties[n] != NULL; n++)
    {
      GDBusPropertyInfo *info = _remote_login_interface_info.parent_struct.properties[n];
      if (info->flags & G_DBUS_PROPERTY_INFO_FLAGS_READABLE)
        {
          GVariant *value;
          value = _remote_login_skeleton_handle_get_property (g_dbus_interface_skeleton_get_connection (G_DBUS_INTERFACE_SKELETON (skeleton)), NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "com.canonical.RemoteLogin", info->name, NULL, skeleton);
          if (value != NULL)
            {
              g_variant_take_ref (value);
              g_variant_builder_add (&builder, "{sv}", info->name, value);
              g_variant_unref (value);
            }
        }
    }
out:
  return g_variant_builder_end (&builder);
}

static void
remote_login_skeleton_dbus_interface_flush (GDBusInterfaceSkeleton *_skeleton)
{
}

static void
_remote_login_on_signal_servers_updated (
    RemoteLogin *object,
    GVariant *arg_serverList)
{
  RemoteLoginSkeleton *skeleton = REMOTE_LOGIN_SKELETON (object);

  GList      *connections, *l;
  GVariant   *signal_variant;
  connections = g_dbus_interface_skeleton_get_connections (G_DBUS_INTERFACE_SKELETON (skeleton));

  signal_variant = g_variant_ref_sink (g_variant_new ("(@a(sssba(sbva{sv})a(si)))",
                   arg_serverList));
  for (l = connections; l != NULL; l = l->next)
    {
      GDBusConnection *connection = l->data;
      g_dbus_connection_emit_signal (connection,
        NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "com.canonical.RemoteLogin", "ServersUpdated",
        signal_variant, NULL);
    }
  g_variant_unref (signal_variant);
  g_list_free_full (connections, g_object_unref);
}

static void
_remote_login_on_signal_login_servers_updated (
    RemoteLogin *object,
    const gchar *arg_uri,
    const gchar *arg_emailAddress,
    const gchar *arg_dataType,
    GVariant *arg_serverList)
{
  RemoteLoginSkeleton *skeleton = REMOTE_LOGIN_SKELETON (object);

  GList      *connections, *l;
  GVariant   *signal_variant;
  connections = g_dbus_interface_skeleton_get_connections (G_DBUS_INTERFACE_SKELETON (skeleton));

  signal_variant = g_variant_ref_sink (g_variant_new ("(sss@a(sssba(sbva{sv})a(si)))",
                   arg_uri,
                   arg_emailAddress,
                   arg_dataType,
                   arg_serverList));
  for (l = connections; l != NULL; l = l->next)
    {
      GDBusConnection *connection = l->data;
      g_dbus_connection_emit_signal (connection,
        NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "com.canonical.RemoteLogin", "LoginServersUpdated",
        signal_variant, NULL);
    }
  g_variant_unref (signal_variant);
  g_list_free_full (connections, g_object_unref);
}

static void
_remote_login_on_signal_login_changed (
    RemoteLogin *object,
    const gchar *arg_uri,
    const gchar *arg_emailAddress)
{
  RemoteLoginSkeleton *skeleton = REMOTE_LOGIN_SKELETON (object);

  GList      *connections, *l;
  GVariant   *signal_variant;
  connections = g_dbus_interface_skeleton_get_connections (G_DBUS_INTERFACE_SKELETON (skeleton));

  signal_variant = g_variant_ref_sink (g_variant_new ("(ss)",
                   arg_uri,
                   arg_emailAddress));
  for (l = connections; l != NULL; l = l->next)
    {
      GDBusConnection *connection = l->data;
      g_dbus_connection_emit_signal (connection,
        NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "com.canonical.RemoteLogin", "LoginChanged",
        signal_variant, NULL);
    }
  g_variant_unref (signal_variant);
  g_list_free_full (connections, g_object_unref);
}

static void remote_login_skeleton_iface_init (RemoteLoginIface *iface);
G_DEFINE_TYPE_WITH_CODE (RemoteLoginSkeleton, remote_login_skeleton, G_TYPE_DBUS_INTERFACE_SKELETON,
                         G_IMPLEMENT_INTERFACE (TYPE_REMOTE_LOGIN, remote_login_skeleton_iface_init));

static void
remote_login_skeleton_finalize (GObject *object)
{
  RemoteLoginSkeleton *skeleton = REMOTE_LOGIN_SKELETON (object);
  g_list_free_full (skeleton->priv->changed_properties, (GDestroyNotify) _changed_property_free);
  if (skeleton->priv->changed_properties_idle_source != NULL)
    g_source_destroy (skeleton->priv->changed_properties_idle_source);
  g_main_context_unref (skeleton->priv->context);
  g_mutex_clear (&skeleton->priv->lock);
  G_OBJECT_CLASS (remote_login_skeleton_parent_class)->finalize (object);
}

static void
remote_login_skeleton_init (RemoteLoginSkeleton *skeleton)
{
  skeleton->priv = G_TYPE_INSTANCE_GET_PRIVATE (skeleton, TYPE_REMOTE_LOGIN_SKELETON, RemoteLoginSkeletonPrivate);
  g_mutex_init (&skeleton->priv->lock);
  skeleton->priv->context = g_main_context_ref_thread_default ();
}

static void
remote_login_skeleton_class_init (RemoteLoginSkeletonClass *klass)
{
  GObjectClass *gobject_class;
  GDBusInterfaceSkeletonClass *skeleton_class;

  g_type_class_add_private (klass, sizeof (RemoteLoginSkeletonPrivate));

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize = remote_login_skeleton_finalize;

  skeleton_class = G_DBUS_INTERFACE_SKELETON_CLASS (klass);
  skeleton_class->get_info = remote_login_skeleton_dbus_interface_get_info;
  skeleton_class->get_properties = remote_login_skeleton_dbus_interface_get_properties;
  skeleton_class->flush = remote_login_skeleton_dbus_interface_flush;
  skeleton_class->get_vtable = remote_login_skeleton_dbus_interface_get_vtable;
}

static void
remote_login_skeleton_iface_init (RemoteLoginIface *iface)
{
  iface->servers_updated = _remote_login_on_signal_servers_updated;
  iface->login_servers_updated = _remote_login_on_signal_login_servers_updated;
  iface->login_changed = _remote_login_on_signal_login_changed;
}

/**
 * remote_login_skeleton_new:
 *
 * Creates a skeleton object for the D-Bus interface <link linkend="gdbus-interface-com-canonical-RemoteLogin.top_of_page">com.canonical.RemoteLogin</link>.
 *
 * Returns: (transfer full) (type RemoteLoginSkeleton): The skeleton object.
 */
RemoteLogin *
remote_login_skeleton_new (void)
{
  return REMOTE_LOGIN (g_object_new (TYPE_REMOTE_LOGIN_SKELETON, NULL));
}

